# Note: These are the default configurations of the plugin
# and do not necessarily mean that players can have a good
# gaming experience. We hope that you will create
# customized configurations based on your own ideas,
# allowing players to experience the uniqueness of your server.

# Vanilla fishing rod properties
FISHING_ROD:
  tag: false
  material: fishing_rod
  effects:
    effect_1:
      type: wait-time-multiplier
      value: 2.0

# Custom rods
copper_fishing_rod:
  material: ItemsAdder:fishing_expansion:copper_fishing_rod
  display:
    name: "<gradient:#e77d56:#ffb59c>Copper Fishing Rod"
    lore:
      - '<gray>A reliable starter rod with a sturdy grip.'
      - ''
      - '<green>⬆ <white>Common <gray>(+15)'
      - '<green>⬆ <white>Rare <gray>(+5)'
  custom-model-data: 1000
  max-durability: 100
  effects:
    effect_1:
      type: wait-time-multiplier
      value: 1.7
    effect_2:
      type: difficulty
      value: -2
    effect_3:
      type: group-mod
      value:
      - common_ow:+15
      - rare_ow:+5

iron_fishing_rod:
  material: ItemsAdder:fishing_expansion:iron_fishing_rod
  display:
    name: "<gradient:#c0c0c0:#ffffff>Iron Fishing Rod"
    lore:
      - '<gray>Well-balanced rod that attracts finer catches.'
      - ''
      - '<red>⬇ <white>Common <gray>(-10)'
      - '<green>⬆ <white>Rare <gray>(+20)'
  custom-model-data: 1001
  max-durability: 250
  effects:
    effect_1:
      type: wait-time-multiplier
      value: 1.5
    effect_2:
      type: difficulty
      value: -4
    effect_3:
      type: group-mod
      value:
      - common_ow:-10
      - rare_ow:+20

golden_fishing_rod:
  material: ItemsAdder:fishing_expansion:golden_fishing_rod
  display:
    name: "<gradient:#ffdf00:#d4af37>Golden Fishing Rod"
    lore:
      - '<gray>A gilded rod that withstands intense heat.'
      - '<#FFFFFF>Can be used for fishing in the <#FFA500>lava</#FFA500>'
      - ''
      - '<red>⬇ <white>Nether Common <gray>(-10)'
      - '<green>⬆ <white>Nether Rare <gray>(+20)'
  custom-model-data: 1004
  max-durability: 85
  effects:
    effect_1:
      type: wait-time-multiplier
      value: 1.3
    effect_2:
      type: lava-fishing
    effect_3:
      type: difficulty
      value: -6
    effect_4:
      type: group-mod
      value:
      - common_nether_univ:-10
      - common_nether_warped:-10
      - rare_nether_univ:+20
      - rare_nether_soul:+20
      - rare_nether_warped:+20

diamond_fishing_rod:
  material: ItemsAdder:fishing_expansion:diamond_fishing_rod
  display:
    name: "<gradient:#00ffff:#ffffff>Diamond Fishing Rod"
    lore:
      - '<gray>An exquisite rod meant for prized treasures.'
      - '<#FFFFFF>Can be used for fishing in the <#FFA500>lava</#FFA500>'
      - ''
      - '<red>⬇ <white>Common <gray>(-15)'
      - '<green>⬆ <white>Rare <gray>(+10)'
      - '<green>⬆ <white>Epic <gray>(+20)'
  custom-model-data: 1002
  max-durability: 500
  effects:
    effect_1:
      type: wait-time-multiplier
      value: 1.1
    effect_2:
      type: difficulty
      value: -8
    effect_3:
      type: lava-fishing
    effect_4:
      type: group-mod
      value:
      - common_ow:-15
      - common_nether_univ:-15
      - common_nether_warped:-15
      - rare_ow:+10
      - rare_nether_univ:+10
      - rare_nether_soul:+10
      - rare_nether_warped:+10
      - epic_reef:+20
      - epic_nether_univ:+20
      - epic_nether_soul:+20

netherite_fishing_rod:
  material: ItemsAdder:fishing_expansion:netherite_fishing_rod
  display:
    name: "<gradient:#4a4a4a:#8b8b8b>Netherite Fishing Rod"
    lore:
      - '<gray>A legendary rod of unparalleled strength.'
      - '<#FFFFFF>Can be used for fishing in the <#FFA500>lava</#FFA500>'
      - ''
      - '<red>⬇ <white>Rare <gray>(-10)'
      - '<green>⬆ <white>Epic <gray>(+10)'
      - '<green>⬆ <white>Legendary <gray>(+20)'
      - '<green>⬆ <white>Mythic <gray>(+10)'
  custom-model-data: 1003
  max-durability: 750
  effects:
    effect_1:
      type: wait-time-multiplier
      value: 1.0
    effect_2:
      type: difficulty
      value: -10
    effect_3:
      type: lava-fishing
    effect_4:
      type: group-mod
      value:
      - rare_ow:-10
      - rare_nether_univ:-10
      - rare_nether_soul:-10
      - rare_nether_warped:-10
      - epic_reef:+10
      - epic_nether_univ:+10
      - epic_nether_soul:+10
      - leg_reef:+20
      - leg_pelagic:+20
      - leg_deep:+20
      - mythical_ow:+10
      - mythical_nether:+10
